### ISSUE TITLE
ProtocolCraft::Slot writes NBT data incorrectly (1.16.3)

### ISSUE THREAD

**Issue by Zwolf8** [adepierre/Botcraft#1]
Example:
```cpp
auto inv = inventory_manager->GetPlayerInventory();
auto slots = inv->GetSlots();
for (int i = 0; i < slots.size(); i++)
{
    auto items = AssetsManager::getInstance().Items();
    auto slot = slots[i];
    auto item = items[slot.GetItemID()];

    if (item->GetName() != "minecraft:air")
    {
        printf("SLOT NBT:\n");
        printf("%s\n", slot.GetNBT().SerializeImpl().serialize(true).c_str());
        printf("Slot: %i, ID: %i, Name: %s, Count: %i\n", i, slot.GetItemID(), item->GetName().c_str(), slot.GetItemCount());
        std::shared_ptr<ProtocolCraft::ClickWindow> Packet(new ClickWindow);
        Packet->SetWindowId(0);
        Packet->SetSlot(i);
        Packet->SetButton(1);
        Packet->SetActionNumber(1);
        Packet->SetMode(4);
        Packet->SetClickedItem(slot);
        network_manager->Send(Packet);

        break;
    }
}
```
(sorry for the messy code)

This code will drop the first item slot in the client. It works fine for any item without NBT data attached to it.

If the item has attached nbt data (ex. flint & steel, enchanted armor, etc.) the server will disconnect you with this:

` Internal Exception: io.netty.handler.codec.DecoderException: io.netty.handler.codec.EncoderException: java.io.IOException: Root tag must be a named compound tag`

Also I love your library had a lot of fun making fun bots with your API =]

**Comment by adepierre** [comment]
I just checked it out, and it fact it's not an issue with ProtocolCraft. If you read the Click Window description on wiki.vg, you'll find that in "drop mode" you actually need to send an "empty slot", not the actual slot value.

A working replacement of the end of your code would be: 
```c++
Slot empty_slot;
empty_slot.SetPresent(false);
Packet->SetClickedItem(empty_slot);
network_manager->Send(Packet);
```

If you want to play with this kind of stuff, you can use my other [SniffCraft](https://github.com/adepierre/SniffCraft) library to print the packets sent between an vanilla client//server. For example with this issue you can very quickly see the expected packet sent by a real cliant:

```js
[0:0:18:18411] [C --> S] Click Window
{
  "action_number": 3,
  "button": 0,
  "clicked_item": {
    "present": false
  },
  "mode": 4,
  "slot": 9,
  "window_id": 0
}
```

Thanks for the love ❤️ And feel free to share your fun bots if you have interesting stuffs!

**Comment by Zwolf8** [comment]
Thanks!
