### ISSUE TITLE
Connecting to LAN games without Mojang Authentication

### ISSUE THREAD

**Issue by Camezza** [adepierre/Botcraft#10]
Offline servers allow you to connect with any username without authenticating with Mojang. This functionality could be implemented into botcraft as currently it makes an authentication attempt even if the password is blank "", and whilst the server is in offline-mode.

**Comment by Camezza** [comment]
I only had this issue on LAN games, worked fine on offline-mode servers

**Comment by adepierre** [comment]
I'm not sure I've understood if there is an issue and what it is exactly. Could you elaborate a bit more and share the steps to reproduce it?
