### ISSUE TITLE
chat signing for 1.19.2

### ISSUE THREAD

**Issue by rom1504** [adepierre/Botcraft#102]
hey, do you have chat signing implemented for 1.19.2 ? if yes I'd be interested to see the code

**Comment by adepierre** [comment]
Hi!

Yes it is supported by botcraft. You can check how the message is signed before it's sent [here](https://github.com/adepierre/Botcraft/blob/master/botcraft/src/Network/NetworkManager.cpp#L172-L206) and more specifically the function computing the signature is [here](https://github.com/adepierre/Botcraft/blob/master/botcraft/src/Network/Authentifier.cpp#L288).

**Comment by rom1504** [comment]
Thanks !

**Comment by adepierre** [comment]
Closing as the answer has been provided. Feel free to reopen if you have more questions about this topic.
