### ISSUE TITLE
[Version request] - 1.12.2

### ISSUE THREAD

**Issue by Kleingebaeck** [adepierre/Botcraft#114]
### Minecraft version

1.12.2

**Comment by adepierre** [comment]
Hmm it look like the tests for 1.12.2 didn't pass because the crafting is broken on this version. I'll try to take a look as soon as I have some time.

Sorry for the inconvenience.

**Comment by adepierre** [comment]
@Kleingebaeck in case you still need it, 1.12.2 compiled version is now available. Sorry for the delay

**Comment by adepierre** [comment]
Closing as resolved
