### ISSUE TITLE
Error running 'Make all'

### ISSUE THREAD

**Issue by Camezza** [adepierre/Botcraft#12]
OS: macOS 10.15.7
GNU Make 3.81

Followed the build steps on the readme and encountered this error:
https://hastebin.com/asuhexamih.csharp

**Comment by adepierre** [comment]
That's strange, it's usually just a warning. You might have to specify to your compiler to count that error as a warning.

**Comment by adepierre** [comment]
Ok so there was actually an error: an incomplete type was wrongly used. However for a reason that's beyond me, it was working fine on MSVC compiler and gcc (> 7) only counted that as a warning. But older gcc versions and clang treated it as an actual error.

They should all be happy now!
