### ISSUE TITLE
protocol only

### ISSUE THREAD

**Issue by randomairborne** [adepierre/Botcraft#13]
Is there a set of the code with only the protocol, for those who want to make seperate renderers?

**Comment by randomairborne** [comment]
lol found it

**Comment by adepierre** [comment]
Yes it's the protocolCraft folder (if someone has the same question in the future)

**Comment by randomairborne** [comment]
Im making a custom client, but I want to use Vulkan rather then OpenGL :)

**Comment by Amatsuki555** [comment]
Wow a custom client

**Comment by randomairborne** [comment]
might not work great, but should at least work for, like, server playing
