### ISSUE TITLE
Is this possible to connect to a microsoft account?

### ISSUE THREAD

**Issue by maxsupermanhd** [adepierre/Botcraft#18]
Unfortunately I have only account that has this new type of registration, will it work? It says `Authentication response returned with status code 403`

**Comment by adepierre** [comment]
Oh I wasn't aware of that. There is indeed another authentication scheme for new accounts, and probably old accounts too once migrated.

Unfortunately, it's not implement in Botcraft yet. Looking at [the wiki](https://wiki.vg/Microsoft_Authentication_Scheme) it looks like it's a lot more complicated than the old system.

Eventually, it should be integrated into botcraft, but it could take a while... Sorry about that.

**Comment by maxsupermanhd** [comment]
Oh damn so I basically must implement oauth? Well, that's pain right there... I will try to do it by hand at least once and implement some helpers like "hey use oauth [y/n]?" and "sending this '...' [y/n]?" for more automated process, there is too many exceptions in new algorithm...
Also can't I just use mojang auth method instead of microsoft ones?

**Comment by maxsupermanhd** [comment]
UHM, nevermind, that was a dumb one, if you have your MC account via Microsoft it will just not accept a username and allow only email of Microsoft linked account...

**Comment by adepierre** [comment]
Yes basically all the oauth flow has to be implemented into botcraft. But I'm not even sure it's possible, as the Microsoft Azure secret id thing should not be shared. So every user of botcraft would have to create one?

I'll try to take a closer look, but it might end up not being possible at all.

**Comment by maxsupermanhd** [comment]
Ok, so it is truly possible to implant a token and other info from Minecraft official launcher (just from a same-formed json in .minecraft) and it will work but it will be cool to make an automated process

**Comment by adepierre** [comment]
If you find a way, even if it's not automated feel free to detail it here so I can try to integrate it, perhaps in a more automated way.

It might not be as ideal as an official oauth implementation, but in the meantime it could still be useful for people with new accounts.

**Comment by maxsupermanhd** [comment]
@adepierre So how I did that:
1. Get official MC launcher installed and create open up a profile in it, it should save it in `launcher_accounts.json` in root folder.
2. From `accounts` take `accessToken` and from `minecraftProfile` inside `accounts` take `id` as your uuid and `name` as your nickname
3. Go to `botcraft/src/Network/Authentifier.cpp` and find method `Authentifier::AuthToken`, comment everything inside and just set `access_token`, `player_display_name` and `player_uuid` from previous step (I've done it via hardcoding it in)
4. Launch a demo or whatever (I launched demo 1 with user control) and supply arguments like `1 mygreatserver.net MyUsername LiterallyAnyPassword` and enjoy your play
https://i.imgur.com/jJttmFn.png (in my case I spawned in proxy-queue thing but it is just like it supposed to be)

**Comment by adepierre** [comment]
Nice thank you! I should be able to add a connection method using only a path to ``launcher_accounts.json`` instead of login/password. That way people with microsoft accounts would also be able to connect, at the cost of logging at least once with the official launcher.

**Comment by adepierre** [comment]
Fixed with 78793e1a8cde90882a48c5c706d8282df3af94c3
