### ISSUE TITLE
Where to find system chat messages?

### ISSUE THREAD

**Issue by maxsupermanhd** [adepierre/Botcraft#19]
I was joining on few servers out in the wild and there is some messages that are not quiet "chat", where I can find hook to them?

Btw, is there a discord server or something for real time / more comfortable chat?

**Comment by adepierre** [comment]
I have no idea of what kind of message you're talking about. But you can use [Sniffcraft](https://github.com/adepierre/SniffCraft) to check which packets are transmitted with a vanilla client.

And no, there is no discord server for Botcraft, but github discussions are enabled.
