### ISSUE TITLE
Lua Scripting API

### ISSUE THREAD

**Issue by Zwolf8** [adepierre/Botcraft#2]
[Lua](https://www.lua.org/about.html) is a popular embedded scripting language.

It would be very awesome if lua scripting was provided in botcraft. It would make the bot creation process a lot easier, no need to compile or anything of that sort.

I recreated the hello world bot example in lua:
```lua
local client = InterfaceClient.new(true, false)
client:SetAutoRespawn(true)
client:Connect(ip, port, login, password)
wait(5)
client:Say("Hi there!")
wait(5)
client:Disconnect()
```

I put together a quick example of how this could work using the [sol2 library](https://github.com/ThePhD/sol2):

```cpp
sol::state lua;
lua.open_libraries(
    sol::lib::base, 
    sol::lib::bit32, 
    sol::lib::coroutine, 
    sol::lib::io, 
    sol::lib::math, 
    sol::lib::os, 
    sol::lib::package, 
    sol::lib::string, 
    sol::lib::table, 
    sol::lib::utf8);


sol::usertype<Botcraft::InterfaceClient> InterfaceClient_bind = lua.new_usertype<Botcraft::InterfaceClient>("InterfaceClient",
    sol::constructors<Botcraft::InterfaceClient(const bool, const bool)>());

lua["wait"] = [](long seconds) -> bool 
{
    std::this_thread::sleep_for(std::chrono::seconds(seconds));
    return true;
};

InterfaceClient_bind["Connect"] = &Botcraft::InterfaceClient::Connect;
InterfaceClient_bind["Disconnect"] = &Botcraft::InterfaceClient::Disconnect;
InterfaceClient_bind["Say"] = &Botcraft::InterfaceClient::Say;
InterfaceClient_bind["Respawn"] = &Botcraft::InterfaceClient::Respawn;
InterfaceClient_bind["SetAutoRespawn"] = &Botcraft::InterfaceClient::SetAutoRespawn;
```

I enjoy the thought of people being able to share their minecraft bots with a short lua script.

**Comment by adepierre** [comment]
I'm affraid that's beyond the scope of what I want to do with this library. I don't know anything about Lua and I'd rather spend the few hours I have to develop new features for botcraft rather than another interface doing the exact same thing.

However I will gladly accept a PR if you want to do it yourself!

**Comment by Zwolf8** [comment]
Sure.

**Comment by Technisha** [comment]
I don't think Lua is the *best* library to use, I'd think something more along the lines of JS would be better tbh (imo)

**Comment by adepierre** [comment]
@Technisha if you are looking for JS bots, you might want to check [mineflayer](https://github.com/PrismarineJS/mineflayer).

**Comment by SaubereSache** [comment]
> @Technisha if you are looking for JS bots, you might want to check [mineflayer](https://github.com/PrismarineJS/mineflayer).

The problem with mineflayer is it's poor code quality and performance, makes it hard to develop complex bots.
A JS Interface for a multithreaded "base client" wouldn't be that useless tbh.

**Comment by Darker** [comment]
The last time I used mineflayer it had better performance than botcraft as far as memory footprint and chunk parse time go. It had slower world pathfinding and looping over blocks was slower also.

**Comment by adepierre** [comment]
> The last time I used mineflayer it had better performance than botcraft as far as memory footprint and chunk parse time go. It had slower world pathfinding and looping over blocks was slower also.

That doesn't really surprise me. Mineflayer is really good and developed by a lot of talented people. I only started to optimize stuff in botcraft last month, and don't really have a performance goal.

**Comment by Zwolf8** [comment]
This feature would probably be more suitable for a separate project, not something in Botcraft itself. C bindings would be a more practical solution, as it could allow any language bindings to be more easily made.
