### ISSUE TITLE
Block vertexes are missalignied, randomly giggles from camera angle change

### ISSUE THREAD

**Issue by maxsupermanhd** [adepierre/Botcraft#24]
Is this supposed to be like that?

**Comment by adepierre** [comment]
Please post detailed description of the problem. There is absolutely no way I can figure out what "like that" means.

**Comment by maxsupermanhd** [comment]
I mean, some parts of textures are missing, some corners of blocks are kinda offset by 0.1 or something similar
![p](https://user-images.githubusercontent.com/20772987/110818769-a20aea00-829e-11eb-85cd-88043219786a.png)

**Comment by maxsupermanhd** [comment]
I mean some corners of blocks are missplaced somehow, like up to 0.1 of a block, some textures are missing or glitching out
![p](https://user-images.githubusercontent.com/20772987/110819001-d4b4e280-829e-11eb-9f52-cf25b093f12d.png)

**Comment by maxsupermanhd** [comment]
![p](https://user-images.githubusercontent.com/20772987/110819168-f9a95580-829e-11eb-9608-955f582db6af.png)

**Comment by maxsupermanhd** [comment]
[2021-03-11 19-22-08.mkv.zip](https://github.com/adepierre/Botcraft/files/6124429/2021-03-11.19-22-08.mkv.zip)
(mkv video zipped)

**Comment by adepierre** [comment]
That sure looks weird. What are your coordinates in the world? This might just be some float imprecision if you're not close to the origin.

Please also remember that this is **not** a library meant to build custom clients that people can play with.

**Comment by maxsupermanhd** [comment]
Well, it's about 380k overworld, maybe it actually, I searched through rendering procedures but did not found any loss or something related to it.

And yes, I'm gonna build my own playable client out of this :grin:

**Comment by adepierre** [comment]
Floats only have a 7 digits precision. So if you are at 380 000 in one direction, this kind of behaviour is quite expected. If you go 1M blocks further it will be even worse.

**Comment by maxsupermanhd** [comment]
Any fix to it? Extended floats?
