### ISSUE TITLE
Cmake glfw3 error

### ISSUE THREAD

**Issue by abasgames** [adepierre/Botcraft#3]
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/abas/Botcraft/build/3rdparty/glfw/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_4e528/fast"
/usr/bin/make -f CMakeFiles/cmTC_4e528.dir/build.make CMakeFiles/cmTC_4e528.dir/build
make[1]: Entering directory '/home/abas/Botcraft/build/3rdparty/glfw/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_4e528.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_4e528.dir/CheckSymbolExists.c.o   -c /home/abas/Botcraft/build/3rdparty/glfw/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_4e528
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4e528.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_4e528.dir/CheckSymbolExists.c.o  -o cmTC_4e528 
/usr/bin/ld: CMakeFiles/cmTC_4e528.dir/CheckSymbolExists.c.o: in function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_4e528.dir/build.make:87: cmTC_4e528] Error 1
make[1]: Leaving directory '/home/abas/Botcraft/build/3rdparty/glfw/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_4e528/fast] Error 2

File /home/abas/Botcraft/build/3rdparty/glfw/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/abas/Botcraft/build/3rdparty/glfw/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_1179c/fast"
/usr/bin/make -f CMakeFiles/cmTC_1179c.dir/build.make CMakeFiles/cmTC_1179c.dir/build
make[1]: Entering directory '/home/abas/Botcraft/build/3rdparty/glfw/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_1179c.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_1179c.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.13/Modules/CheckFunctionExists.c
Linking C executable cmTC_1179c
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_1179c.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_1179c.dir/CheckFunctionExists.c.o  -o cmTC_1179c -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_1179c.dir/build.make:87: cmTC_1179c] Error 1
make[1]: Leaving directory '/home/abas/Botcraft/build/3rdparty/glfw/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_1179c/fast] Error 2

**Comment by adepierre** [comment]
Could you please provide some information on your build? At least the OS and the options you used for the build so I can try to reproduce it? Thanks!

**Comment by abasgames** [comment]
cmake -DBOTCRAFT_INSTALL_ASSETS=ON -DBOTCRAFT_USE_IMGUI=ON -DGAME_VERSION=1.16.3 -DBOTCRAFT_BUILD_EXAMPLES=ON -DBOTCRAFT_COMPRESSION=ON -DBOTCRAFT_ENCRYPTION=ON -DBOTCRAFT_USE_OPENGL_GUI=ON ..
make all
Parrot os amd64
And another machine runs ubuntu 16.04
Both same error

**Comment by adepierre** [comment]
Ok it's a strange one. I do have the same ``CMakeError.log`` file created in my build folder but it doesn't prevent the actual build to complete. I think it's not the actual cause of your build error.

I wonder if the culprit here is a missing OpenGL library. I assumed it was installed by default, but perhaps it's not the case on your config?

**Comment by abasgames** [comment]
Reclone the git seems fix it
