### ISSUE TITLE
killaura example?

### ISSUE THREAD

**Issue by maxsupermanhd** [adepierre/Botcraft#31]
For mob farms will be great to have simplest hostile mobs killaura example for easy deploy

**Comment by adepierre** [comment]
I'm not sure what killaura is exactly, but yeah I'm currently working on entity handling. So pickup items/attack mobs should become part of the possibilities.

But Minecraft's entity system is not that simple and I need to find a kind of nice way to implement it in the library.

**Comment by maxsupermanhd** [comment]
By killaura I mean automatic attack of entities that are getting in range to the player (unobstructed, visible). Also Will be great to have something like setting angles of the camera and attack interval so bot can join, look at specific angles and just left click on interval

**Comment by adepierre** [comment]
You can already use the library to set the position of the camera. See for example the [user controlled example](https://github.com/adepierre/Botcraft/blob/cc7b02603cd66a34bf4854bede2704ae2c21aaab/Examples/1_UserControlledExample/src/UserControlledClient.cpp#L293).

**Comment by maxsupermanhd** [comment]
What about attacking entity or basically left click action?

**Comment by adepierre** [comment]
Once more: entities are not processed at the time. So there is no usable representation of them in botcraft.

And there is no such thing as "left click action" actually. Currently, there is a support for digging, which is also a "left click action" but that's a totally different thing and packets from attacking, which is also a "left click action".

**Comment by maxsupermanhd** [comment]
Any news? I've noticed EntityManager but I may not understand complete "attack" mechanism, I should send UseItem packet to use sword or how can I figure this out by myself? (PS yes, I want to implement this now)

**Comment by adepierre** [comment]
Nothing new no.

You can use sniffcraft to check which packets are sent by a vanilla client.

**Comment by maxsupermanhd** [comment]
So I investigated for a bit and basically when player attacks something it sends out attack packet as a `Interact Entity` with entity id (already present in EntityManager), player sneaking or not and type as 1 (type 2 seems to be "use" or "interact") regardless of what weapon is used (or fists). Followed by `Animation (serverbound)` but I assume this one is optional and only affects ... well ... animation. I think I am getting here, I can just from time to time check if there is any mob in some coordinate range and send attack packet. It automatically swings sword too and damages everything around on server.
