### ISSUE TITLE
How to Install?

### ISSUE THREAD

**Issue by NFKRZZ** [adepierre/Botcraft#32]
Sorry if this is a stupid question but I tried opening this project in visual studio and doing the cmake thing which I think just builds the .lib files. I then referenced the .lib files and the header files in a new visual studio project. But I just keep on getting thrown errors saying that a bunch of new source files are missing and it cant open the include files I did list. Any help would be appreciated.

**Comment by adepierre** [comment]
There is no such thing as a stupid question.

Could you please elaborate on what you did and what the error was? What did you reference in your VS project exactly?

That would be easier to help you with these informations!

**Comment by adepierre** [comment]
Closing it as there is not much that can be done without more information. Feel free to reopen with more details.
