### ISSUE TITLE
Timeout from server after 15 seconds

### ISSUE THREAD

**Issue by maxsupermanhd** [adepierre/Botcraft#39]
I am trying to run example 2 on a local vanilla server and it does not work. It seems there is some heavy enough task to keep 1 core occupied for more that 15 seconds after logging on. Testing on Apple MacBook 13 inch Core 2 Duo (running server in background too) (upgraded to 16GB of ram so no issues here). Tried to interrupt with gdb and look what is causing trouble but only facing timers.
Any idea on this? 
![pic](https://user-images.githubusercontent.com/20772987/124313927-3fee3180-db7a-11eb-8e00-b8418c1f127e.png)

**Comment by adepierre** [comment]
Yep I've already seen this behaviour when CPU is too slow to process all the chunk data coming from the server when connecting.

You can confirm that using example 3, where data are not processed. In this case the server should not TO you.

**Comment by maxsupermanhd** [comment]
Is this possible to make this chunk processing non-blocking or disable it all together? In my application I don't really need world to be present, I already know all block locations and I don't need to move anywhere. Just log-in, use lever, exit.

**Comment by adepierre** [comment]
Technically you can disable the processing of the world packets in a similar fashion to [this line](https://github.com/adepierre/Botcraft/blob/5ec0914cf9447f9bdda93b9ccfe5cbbe806868b6/botcraft/src/Game/BaseClient.cpp#L369). It won't prevent you from using ``InteractWithBlock``, but you have to know the location of the lever before, as you can't get it from the world.

**Comment by maxsupermanhd** [comment]
Can this handler be in other thread too just like physics and networking?

**Comment by maxsupermanhd** [comment]
Also if afk-only flag is set will interactions work? Interaction is just a packet and and animation, should just work...

**Comment by adepierre** [comment]
That's alreay on the network processing thread, but technically yes it could be transferred to a more specialised thread.

And yes, all interactions should work with afk-only as you only send information, you don't need any from the server.

**Comment by adepierre** [comment]
I've added the possibility to use another thread to process the packets handled by the ``World`` class. However, it means that every packet is copied once, so it's not activated by default. You can change the behaviour by switching the second bool to true when creating a ``World`` object.

https://github.com/adepierre/Botcraft/blob/9566f40d126271cf47908e5dd5e0159fdc818b8e/botcraft/src/Game/BaseClient.cpp#L371
