### ISSUE TITLE
Undefined reference?

### ISSUE THREAD

**Issue by tale** [adepierre/Botcraft#41]
Hey, sorry I know this is probably a really stupid question but everytime I try to link I get `undefined reference to `Botcraft::BaseClient::Handle(ProtocolCraft::ClientboundContainerAckPacket&)`. I'm really sorry I know there's probably a simple solution that I'm missing out on but everytime I run make i encounter this error.

Right now I have an empty main file but my files look something like this:
```c++
#include <iostream>
#include "KitteaMinecraftClient.h"

using namespace Botcraft;
using namespace ProtocolCraft;

KitteaMinecraftClient::KitteaMinecraftClient(const bool use_renderer_, const bool is_afk_) : InterfaceClient(use_renderer_, is_afk_) {

}

KitteaMinecraftClient::~KitteaMinecraftClient() {

}

void KitteaMinecraftClient::Handle(ClientboundChatPacket &msg) {
    Botcraft::BaseClient::Handle(msg);
}
```

```cpp
#pragma once
#include <botcraft/Game/InterfaceClient.hpp>

class KitteaMinecraftClient: public Botcraft::InterfaceClient {
public:
    KitteaMinecraftClient(const bool use_renderer_, const bool is_afk_);
    ~KitteaMinecraftClient();

protected:
    virtual void Handle(ProtocolCraft::ClientboundChatPacket &msg) override;
};
```

```cmake
cmake_minimum_required(VERSION 3.16)
project(kittea_bot)

set(CMAKE_CXX_STANDARD 20)
add_executable(kittea-bot src/main.cpp src/KitteaMinecraftClient.cpp)
target_link_directories(kittea-bot PUBLIC /usr/local/bin)

target_link_libraries(kittea-bot dpp)
target_link_libraries(kittea-bot botcraft)
target_include_directories(kittea-bot PRIVATE
        include
)

set_target_properties(kittea-bot PROPERTIES
        CXX_STANDARD 20
        CXX_STANDARD_REQUIRED ON
)
```

**Comment by adepierre** [comment]
Could you try to also link to protocolCraft? That's the library in which the protocol is defined, and it should solve your problem.

**Comment by tale** [comment]
Even if I add `target_link_libraries(kittea-bot protocolCraft)` it doesn't help me in any way

**Comment by adepierre** [comment]
And a compiled version of both botcraft and protocolCraft are indeed present in your ``/usr/local/bin`` path?

Also I just noticed that you're not including the header folder for botcraft, did you copy it in your local include folder? Otherwise you have to also add a ``target_include_directories`` for either the include folders of botcraft, protocolCraft and picoJson, or the include folder obtained after you installed botcraft (which should contain three folders ``botcraft``, ``protocolCraft`` and ``picoJson``).

**Comment by tale** [comment]
Only libbotcraft.so is in /usr/local/bin but libprotocolCraft.a is in /usr/local/lib
And yes I've copied the headers myself.

**Comment by tale** [comment]
Also if I use the headers at /usr/local/include I just get a bunch of #error "Protocol version not implemented"

**Comment by adepierre** [comment]
Yeah there are some preprocessors like ``PROTOCOL_VERSION`` that need to be defined. Usually it's done by cmake when you ``find_package`` botcraft, but as you are linking the stuff manually you have to define them yourself.

I can't reproduce your issue on Windows, I'll try later on Linux.

**Comment by tale** [comment]
Alright, thank you for responding, once again I'm sorry if this is a stupid question.

**Comment by tale** [comment]
On second thought is it possible to use this in a CMake project instead of having to install it to system?

**Comment by adepierre** [comment]
Yes. You can either use it directly by the source to your project and call ``add_subdirectory``, or use cmake ``find_package`` command to get the installed library (you _might_ have to give cmake a location, I'm not sure about how linux works with this kind of stuff).

However, now that I mention it, I haven't tested the cmake installation stuff for a while, and I'm not sure it's still working. But using cmake ``add_subdirectory`` on the source folder should work properly.

**Comment by tale** [comment]
Nah, Cmake doesn't work because it can't compile the dependencies, it expects `3rdparty` and `cmake` to be in my root folder which creates an absolute mess everywhere.

**Comment by adepierre** [comment]
Yeah true. I will try some things today and let you know what I find.

**Comment by tale** [comment]
Thank you, I appreciate you taking the time for this.

**Comment by adepierre** [comment]
Could you retry with the latest version? Now all path should be relative to the botcraft folder instead of the main cmake folder.

**Comment by tale** [comment]
It works! Thank you so much.
