### ISSUE TITLE
Add example on how to use Botcraft to PLAY minecraft

### ISSUE THREAD

**Issue by THEGODFATHERRX** [adepierre/Botcraft#48]
I want to use Botcraft to play minecraft normally, like with a mouse and keyboard to interact with the world, how do I do that? all I see in examples is code that is being used to bot minecraft. 

could you post code that shows how to do that?

**Comment by adepierre** [comment]
[Example 1](https://github.com/adepierre/Botcraft/tree/master/Examples/1_UserControlledExample) does precisely that. But keep in mind that the capabilities are very limited (you can use your mouse and keyboard to move/break blocks/see what's inside your inventory but not much more). Botcraft is a library to create bots, not to replace the client.
