### ISSUE TITLE
don't load some chunks and can't move in survival mode

### ISSUE THREAD

**Issue by fulcanelly** [adepierre/Botcraft#49]
![Screenshot_2021-08-19_01-06-38](https://user-images.githubusercontent.com/53056797/129978825-f5ee4460-5724-4077-a5c5-e1eb0ff4da22.png)

does it at all support survival mode ?

**Comment by adepierre** [comment]
Yes it totally works in survival, the mapart gif on the readme was created with 10 bots playing in survival mode.

That being said, there is not much debug information in a screen, but from what I can see my best guess would be that you are trying to play on a server that does not allow bots and therefore uses anti-bot techniques. My advice in this case would be: respect the server owner(s) and don't use bot on this server.

However, if this is your server, please share a detailed way I could reproduce the bug (vanilla server? Modded? Which mods etc...)

**Comment by fulcanelly** [comment]
No, it's entirely my server, it uses FlameCord with ViaVersion + ViaBackwards for proxy and two (one for loby one for game) [AirplanePurpur](https://github.com/TECHNOVE/Airplane/tree/purpur/1.17) for core. It has nothing like anti-bot techniques except default paper's anti-x-ray, which you can notice by random block bundle.

**Comment by adepierre** [comment]
Ok thanks for the details, I'll try to reproduce the issue to see what's going on. If you could give some links to download the server jar and the mods and config files it will be easier for me rather than searching every word you gave 😀

Yeah the x-ray random ore blocks was the fact that made me think that there was some anti-cheat going on

**Comment by adepierre** [comment]
Sorry for the delay, I didn't have much time lately to deal with that.

I've tried to reproduce the issue, but unfortunately I haven't been able to using the information you gave me. If you remember, could you share a detailed process to reproduce the issue? Thanks

**Comment by adepierre** [comment]
Closing as there is not much more that can be done without further information. Feel free to reopen if you have anything to add to help track down this issue.
