### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by Camezza** [adepierre/Botcraft#5]
I ran into an error while following the build instructions, any help would be appreciated. :)

OS: Ubuntu 20.04.1 LTS 64 bit

Used the following CMake variables:
GAME_VERSION=1.16.3 
BOTCRAFT_INSTALL_ASSETS=ON 
BOTCRAFT_BUILD_EXAMPLES=ON
BOTCRAFT_COMPRESSION=ON
BOTCRAFT_ENCRYPTION=ON

Error occured while running `make all`:
https://pastebin.com/XerM1hmF

**Comment by adepierre** [comment]
I didn't know about this ``position independant code`` thing as it doesn't exist on windows and for a strange reason doesn't seems to exist on my raspberry...

Could you try to add this on line 272 of ``protocolCraft/CMakeLists.txt`` and tell me if it solves your issue?

```cmake
set_property(TARGET protocolCraft PROPERTY POSITION_INDEPENDENT_CODE ON)
```

**Comment by Camezza** [comment]
Yep, that seemed to fix it. Cheers

**Comment by adepierre** [comment]
Glad to hear it :)
