### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range' when using Hello World Example

### ISSUE THREAD

**Issue by portalthree** [adepierre/Botcraft#55]
I'm using the default 0_HelloWorldExample but when i try to run it, i get this error
```Starting connection process
Trying to connect to 127.0.0.1:25565
Connected to server.
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)```
It does connect, but instantly disconnects right after

**Comment by GaspardCulis** [comment]
Hi, I got the same issue in 1.19.2 with the default mojang server, worked fine with the **ConnectionCient**  but as soon as I switched to the **SimpleBehaviourClient** to implement pathfinding, i got that error :

`terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Abandon`

I used the example template project, and in my main.cpp I have :

#include <iostream>
#include <thread>
#include <chrono>

#include <botcraft/AI/Tasks/PathfindingTask.hpp>
#include <botcraft/AI/SimpleBehaviourClient.hpp>

using namespace std;

int main(int argc, char* argv[])
{

    Botcraft::SimpleBehaviourClient client(false);

    client.Connect("localhost:25565", "Bot");
    cout << "This message will show up" << endl;
    std::this_thread::sleep_for(chrono::milliseconds(5000));
    cout << "This one won't" << endl;
    Botcraft::Position target(21, 114, 242);
    client.SendChatMessage("Letsss goooo");
    Botcraft::GoTo(client, target);
    client.SendChatMessage("Yo I here");
    this_thread::sleep_for(chrono::milliseconds(5000));
    client.Disconnect();

    return 0;
}


I'm running : 
Linux version 5.15.0-46-generic (buildd@lcy02-amd64-007) (gcc (Ubuntu 9.4.0-1ubuntu1\~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) \#49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022

**Comment by adepierre** [comment]
@GaspardCulis I can't check in details right now, but you shouldn't call the GoTo function like that, it's meant to be use as a leaf of a behaviour tree.

You can check [example 5](https://github.com/adepierre/Botcraft/blob/master/Examples/5_MobHitterExample/src/main.cpp#L73) to see how to create a very simple tree, or the [wiki page](https://github.com/adepierre/Botcraft/wiki/Behaviour-system) for more details about the behaviour system.

If you still have an issue when using GoTo in a tree, please post your updated main.cpp and I'll try to take a look when I have some time.

**Comment by GaspardCulis** [comment]
I think goto isn't causing this issue, u commented out the pathfinding part, leaving only the connection and the sleep function , still had this error

**Comment by adepierre** [comment]
I tried to run your main.cpp and I don't have any issue:

```bash
[2022-09-16 18:23:18.339] [INFO] [NetworkIOService(17092)] TCP_Com.cpp(93): Connected to server.
This message will show up
This one won't
```

@GaspardCulis Does the issue happens on a brand new server or only on one you already played? If so would you mind to upload your world somewhere?

**Comment by GaspardCulis** [comment]
A brand new 1.19.2 mojang official server, offline mode to false, and that's all there is to it

**Comment by adepierre** [comment]
I don't think so if it compiles it without complaining. Is there any way you could try to compile it in debug (-DCMAKE_BUILD_TYPE=Debug) and run it with gdb to get a stack trace? That could give a hint where the problem happens.

**Comment by GaspardCulis** [comment]
Did your thing, first :
`cmake -DGAME_VERSION=latest -DBOTCRAFT_COMPRESSION=ON -DBOTCRAFT_ENCRYPTION=ON -DBOTCRAFT_USE_OPENGL_GUI=OFF -DCMAKE_BUILD_TYPE=Debug`

Then :
`make all`

FInally :
For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) file Test
Reading symbols from Test...
(gdb) run
Starting program: /home/gaspard/Programmation/c++/BotCraft/bin/Test 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
[2022-09-19 08:42:41.936] [INFO] [(140737326171968)] AssetsManager.cpp(26): Loading blocks from file...
[2022-09-19 08:42:46.182] [INFO] [(140737326171968)] AssetsManager.cpp(28): Done!
[2022-09-19 08:42:46.182] [INFO] [(140737326171968)] AssetsManager.cpp(29): Loading biomes from file...
[2022-09-19 08:42:46.185] [INFO] [(140737326171968)] AssetsManager.cpp(31): Done!
[2022-09-19 08:42:46.185] [INFO] [(140737326171968)] AssetsManager.cpp(32): Loading items from file...
[2022-09-19 08:42:46.201] [INFO] [(140737326171968)] AssetsManager.cpp(34): Done!
[2022-09-19 08:42:46.201] [INFO] [(140737326171968)] AssetsManager.cpp(44): Clearing cache from memory...
[2022-09-19 08:42:46.218] [INFO] [(140737326171968)] AssetsManager.cpp(46): Done!
[New Thread 0x7ffff64d4640 (LWP 3504)]
[2022-09-19 08:42:46.229] [INFO] [(140737326171968)] TCP_Com.cpp(28): Trying to connect to localhost:25565
[New Thread 0x7ffff5cd3640 (LWP 3508)]
[2022-09-19 08:42:46.230] [INFO] [NetworkIOService(140737317254720)] TCP_Com.cpp(93): Connected to server.
[New Thread 0x7ffff54d2640 (LWP 3509)]
[Thread 0x7ffff54d2640 (LWP 3509) exited]
[Thread 0x7ffff5cd3640 (LWP 3508) exited]
[Thread 0x7ffff64d4640 (LWP 3504) exited]
[Inferior 1 (process 3475) exited normally]
(gdb) 

So it worked with gdb, but the regular executable still crashed

**Comment by adepierre** [comment]
Hmm that's weird. I'm not that used to gcc so I wouldn't know why it doesn't behave the same. As an alternative maybe you could try to wrap your main in a try catch and use something like [that](https://gist.github.com/fmela/591333/0e8f9f123c87c1f234cd3050b2dac9c76185bdf1) to get a stacktrace? Because without the origin of the bug or a way to reprduce it on my side it's kind of hard to debug unfortunately 😕

**Comment by GaspardCulis** [comment]
Okay, maybe I'll try another compiler, I'll keep you informed.

**Comment by GaspardCulis** [comment]
How am I supposed to build the default example project ?

**Comment by adepierre** [comment]
> How am I supposed to build the default example project ?

Using the commands [on the readme](https://github.com/adepierre/Botcraft#building) should work. By defaults the compiled examples will be in ``bin`` folder.

**Comment by GaspardCulis** [comment]
Still not working I'm sad. What development environment are you using ?

**Comment by adepierre** [comment]
I test it both on Windows with MSVC and on Ubuntu 20.04 with g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 and both are working fine.

Maybe it's an issue with a zlib or openssl library on your system? You could try to disable the features by setting  ``-DBOTCRAFT_COMPRESSION=OFF -DBOTCRAFT_ENCRYPTION=OFF`` and setting ``network-compression-threshold`` to -1 in the server.properties file.

Also try to start from a fresh clone folder of botcraft so once you have a working setup you can try to add things one by one until you find which one is breaking things.

**Comment by adepierre** [comment]
@GaspardCulis Any news about your issue?

**Comment by GaspardCulis** [comment]
Still not working I'm sad. I am currently running it with gdb it's the only way I made it work, but I'm taking a little break for this project right now

**Comment by adepierre** [comment]
Ok so I'll just close this issue as there is not much that can be done right now. Feel free to reopen when you get back to your project!
