### ISSUE TITLE
add GetShouldBeClosed to BaseClient too

### ISSUE THREAD

**Issue by maxsupermanhd** [adepierre/Botcraft#57]
Why it is present only on interface client?

**Comment by adepierre** [comment]
There will be some modifications of all XXXClients with the new behaviour system (arriving soon-ish maybe perhaps I hope). I'll try to move the should_be_closed bool to a higher level in the hierarchy.

Concerning your second point, could you elaborate on how to reproduce this kind of disconnection? When the server kicks the player or when the connection is lost?

**Comment by maxsupermanhd** [comment]
I believe server just drops connection silently and does not even close socket. I experienced such "drops" on regular and hacked clients and both of them timeout after 30 seconds of last ping/tick from server, most likely considering socket dead.

**Comment by adepierre** [comment]
Fixed with the new Client organization
