### ISSUE TITLE
No entity information

### ISSUE THREAD

**Issue by maxsupermanhd** [adepierre/Botcraft#61]
Would be cool to have entity manager parse entity data packets in order to get what entities are, want to make a simple player detector that will log players and chat on the server.

**Comment by adepierre** [comment]
Yes I'm working on the entity system.

**Comment by folkertvanheusden** [comment]
Is this working? Because if I do GetFrom on a chat-message, I always get an empty string. Also going through all entities and retrieving their GetName gives "Trying to load metadata in unexisting entity".
