### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by techtechnikov** [adepierre/Botcraft#68]
`/home/kenguru/Botcraft/botcraft/src/Network/Authentifier.cpp:692:31: error: ‘sleep_for’ is not a member of ‘std::this_thread’
  692 |             std::this_thread::sleep_for(std::chrono::seconds(pool_interval + 1));`
may be is necessary to add '#include <thread>' and '-D_GLIBCXX_USE_NANOSLEEP'?

**Comment by adepierre** [comment]
Try #67 sent this morning, I didn't have the time to review it yet, but I think it fixes the issue.

**Comment by techtechnikov** [comment]
Thank you.
