### ISSUE TITLE
Undefined reference to Botcraft

### ISSUE THREAD

**Issue by Camezza** [adepierre/Botcraft#7]
Hello, I get [this error](https://hastebin.com/ovobelalaj.cpp) when compiling the following code:
https://hastebin.com/lakiruvude.cpp

**Comment by adepierre** [comment]
I gues you added the include folders correctly to your projects but you forgot to link to the library. It's difficult to say without knowing what command you used for the compilation.

**Comment by Camezza** [comment]
I used
`/snap/clion/126/bin/cmake/linux/bin/cmake --build /home/mezza/Documents/C++/mccpp/cmake-build-debug --target mc -- -j 3`

**Comment by adepierre** [comment]
This actually doesn't show how you add the include folders and link to the library.

**Comment by Camezza** [comment]
Ah sorry, i'm still relatively new to c++ and have trouble understanding some of the concepts involved. Do you only need the `#include <botcraft/Game/InterfaceClient.hpp>` part or is there something i'm still missing?

**Comment by Camezza** [comment]
The library was installed to the default location at /usr/local, I assumed that the compiler looked there automatically for references

**Comment by adepierre** [comment]
No the ``.hpp`` files are just one part. If the library is ``header only``, you're done, but if the library includes some ``.cpp`` files (like botcraft), you also need to give your compiler the compiled library file.

If you and the library are using cmake, everything can be done automatically with one line. In the example:
https://github.com/adepierre/Botcraft/blob/6adad2920e2b7ecf8dbc154f97d34ed17344a9c4/Examples/0_HelloWorld/CMakeLists.txt#L11

If not you have to give it to your compiler manually. I suggest you to try to learn about libraries and how to link in cpp, it will surely be useful more than once!
