### ISSUE TITLE
Unable to locate Assets folder

### ISSUE THREAD

**Issue by Camezza** [adepierre/Botcraft#8]
Whenever I compile & run main.cpp, I get the following pathing error: 
https://hastebin.com/viduniyuto.sql

Source code: https://github.com/Camezza/mccpp/
Any help would be appreciated!

**Comment by adepierre** [comment]
The assets folder is usually set by cmake as a preprocessor variable here : 

https://github.com/adepierre/Botcraft/blob/6adad2920e2b7ecf8dbc154f97d34ed17344a9c4/CMakeLists.txt#L48
https://github.com/adepierre/Botcraft/blob/6adad2920e2b7ecf8dbc154f97d34ed17344a9c4/botcraft/CMakeLists.txt#L151

As your cmake doesn't seems to take the preprocessor set by cmake, you'll need to set them manually.

**Comment by Camezza** [comment]
After defining a new path in [CMakeLists.txt](https://github.com/Camezza/mccpp/blob/master/CMakeLists.txt) and setting a preprocessor for ASSETS_PATH, the path doesn't update and remains `../Assets/${GAME_VERSION}`.

**Comment by adepierre** [comment]
I'm sorry I think I wasn't clear enough. You need to define the ``ASSETS_PAH`` preprocessor when compiling the botcraft library. Then, when you are using the library in your program, you don't need to define it again. You only need to ensure that there is indeed the assets at the relative location ``../Assets/1.16.3/`` (if you compiled for 1.16.3 version).
