### ISSUE TITLE
Can you make a detailed installation tutorial ?

### ISSUE THREAD

**Issue by YoYomec** [adepierre/Botcraft#88]
Hello.
Can you make a detailed installation tutorial assuming that the pc is blank without any program such as git installed ?

**Comment by adepierre** [comment]
Hi!

Yes absolutely. I have been thinking about doing that for quite some time now, but never took the time. I'll try to do it this week-end.

**Comment by adepierre** [comment]
The first version of the detailed guide is available in the [wiki section](https://github.com/adepierre/Botcraft/wiki/Detailed-installation-guide).

If you try to follow it, could you please give some feedback about what parts are unclear? It's not easy for me to know to what extent each point should be detailed so it's accessible to almost anyone who'd like to test botcraft examples.

**Comment by YoYomec** [comment]
Ok, I will read it, thank you ! 👍

**Comment by YoYomec** [comment]
Just one thing, you are french ?

**Comment by YoYomec** [comment]
After the instalation, i have an error :
![image](https://user-images.githubusercontent.com/98414804/175805999-3f44eb2c-61f5-4cde-a336-c6722247e97a.png)

**Comment by adepierre** [comment]
> Just one thing, you are french ?

Yes, but I'd like to keep the discussion in english so people can follow more easily if they have the same issue.

> After the instalation, i have an error :

Could you open cmake, make sure ``Grouped`` and ``Advanced`` are checked (just below where you entered the build path) and then open the ``ZLIB`` section and take a screenshot?

**Comment by YoYomec** [comment]
this is :
![image](https://user-images.githubusercontent.com/98414804/175814403-c9b549de-806c-4881-932d-3b2fa4be4a81.png)

**Comment by adepierre** [comment]
You forgot to tick the Grouped and Advanced checkboxes. There is no info about ZLIB on your image

**Comment by YoYomec** [comment]
so what i can do to resolve it ?

**Comment by adepierre** [comment]
Make sure the two checkboxes are ticked in cmake, open the ZLIB section and send a new screenshot with the ZLIB section included.

**Comment by YoYomec** [comment]
it is this ?
![image](https://user-images.githubusercontent.com/98414804/175815214-da190010-41d4-454f-ade4-6215afba6e6c.png)

**Comment by YoYomec** [comment]
it is this ?
![image](https://user-images.githubusercontent.com/98414804/175815257-96a49623-5650-468f-8e08-47fe81bab2f6.png)

**Comment by YoYomec** [comment]
no, it's this...
![image](https://user-images.githubusercontent.com/98414804/175815339-69adf0d2-abb2-4b99-90af-7cbf1daf37bf.png)

**Comment by adepierre** [comment]
Ok I see what's going on, cmake linked the dynamic library instead of the static one. I'll try to find a fix. In the meantime you can go to ``build/3rdparty/zlib/install/bin`` and copy ``zlib.dll`` into the bin folder, next to ``botcraft.dll`` and all the exe files and it should fix the error message.

**Comment by adepierre** [comment]
It should be good. With the latest version of the code cmake should pick the static version of zlib and you shouldn't get the error message anymore. Could you let me know if it works for you?

Make sure you start from a clean state (at least, close cmake and delete your entire build folder before reopening cmake).

**Comment by adepierre** [comment]
Closing as no response. Feel free to reopen if something is not clear enough in the tutorial.
