### ISSUE TITLE
[enhancement] Attach built versions aka releases to github

### ISSUE THREAD

**Issue by godlikeSwan** [adepierre/Botcraft#89]
It would be very helpful for just using as soon as Visual Studio is very heavy and it's installing so slowly

**Comment by godlikeSwan** [comment]
found this
https://github.com/adepierre/Botcraft/issues/81#issuecomment-1060675936

**Comment by adepierre** [comment]
Hello!

This is unfortunately not possible, as during the build process some minecraft assets are downloaded (textures, block models etc...) and it's not allowed to redistribute them directly.
