### ISSUE TITLE
Connecting to a DNS configured server

### ISSUE THREAD

**Issue by Camezza** [adepierre/Botcraft#9]
I'm attempting to connect to a server with a DNS (Hypixel.net, for example) but receive the error:
`Error when connecting to server. Error code :asio.system:125`

One workaround I found was to get the ip from a ping request, but this only worked for servers without dns encryption.

**Comment by adepierre** [comment]
Oh that's an interesting case indeed. I didn't thought about it but yeah that should be doable (as the vanilla client does it :p).

I'm working on another functionality at the moment but I'll definitely check it out as soon as I have a bit of time.

**Comment by Camezza** [comment]
Sounds good 👍

**Comment by adepierre** [comment]
So I have been searching for information about that, and according to what I found, it seems that the translation from hostname to ip:port is done through a DNS SRV record with a _minecraft._tcp prefix (see for example [this link](https://www.noip.com/support/knowledgebase/how-to-add-a-srv-record-to-your-minecraft-server-remove-the-port-on-the-end-of-the-url/) explaining how to set it up).

However, asio does not support SRV queries and I don't really want to add another entire library just for this usecase. I'll keep looking to try to see if it's possible to do the request manually using asio.

**Comment by adepierre** [comment]
Should be working now with bf6728a. There is still an error when trying to join Hypixel but it's on protocolCraft side. I'll try to check it later.
