### ISSUE TITLE
Publish the project to vcpkg

### ISSUE THREAD

**Issue by Neboer** [adepierre/Botcraft#93]
As we all know, vcpkg is a good place for developers to share their projects on. It is super convenient for users to get a ready-to-use package on windows without complicate configurations. Could you please share the project Botcraft and Protocolcraft on vcpkg? It will be very nice! Thank you.

**Comment by adepierre** [comment]
Hello!

I don't really know a lot about vcpkg so I guess that would be a good opportunity for me to learn. There are two things that could be potential issues though:

- MC versions: currently, botcraft and protocolCraft are available for 24 MC versions (from 1.12.2 to 1.19). It means that for each botcraft/protocolCraft update, I need to compile it 24 times and generate 48 different vcpkg. Of course I guess it could be fully automatized, but it looks like a lot of compilation server time (it's ~20 minutes per compilation, so for all 24 versions, it would mean 8 hours of server time per botcraft update). And the number of MC versions will probably keep growing in the future. Aside from the compilation, it would probably be a mess to have 24 vcpkg for one project, do you know if there is support for this kind of things?
- Assets redistributions: that's the same issue I have for the release. At compilation time, you only need the library file, but at runtime, you also need the assets. Some are from botcraft, these ones can be packaged with the library without issues, and some from minecraft, like textures of block models, that can't, for legal reasons. With cmake, I just made the build process download the minecraft jar, extract the required assets and copy them at the right location. But I'm not sure this is possible with vcpkg?

**Comment by adepierre** [comment]
Wait, does vcpkg require compiled files or just source code and perform the build itself? In the later case the issues above are not a problem any more.

**Comment by Neboer** [comment]
Yes you are right, vcpkg is NOT a normal package manager, the package is built durling the user installing process.

**Comment by Neboer** [comment]
For the first question, I will ask humbly is it possible for a user to have two different minecraft versions of botcraft (the botcraft itself is of the same version) being used on a same project at the same time?

**Comment by adepierre** [comment]
> Yes you are right, vcpkg is NOT a normal package manager, the package is built durling the user installing process.

Ok so that should be feasible I guess. Do you know what is roughly the path to follow to make a repo "vcpkg compliant"? What's preventing doing vcpkginstall(botcraft repo url) right now?

> is it possible for a user to have two different minecraft versions of botcraft (the botcraft itself is of the same version) being used on a same project at the same time?

I never tried it, but I would say it's not possible due to duplicate symbols. Maybe if you're extra careful with naming 🤔

**Comment by Neboer** [comment]
> I never tried it, but I would say it's not possible due to duplicate symbols. Maybe if you're extra careful with naming 🤔

I suggest you to publish 24 vcpkg packages at the same time. The package can be named like: botcraft-1.18.1. Any two of the package are not compatible, so users are forced to have only one mc version of botcraft installed. I'm not familiar with vcpkg either, so I am trying to find a way to solve the problem. Botcraft is quite a special library so it's a bit confusing.

**Comment by adepierre** [comment]
So I took some time investigating vcpkg and what it would take to add botcraft to it. Below are my thought about it, but tl;dr is that I don't find it worth the time doing it.

- I don't really see the benefit of adding botcraft to vcpkg. The main point of vcpkg is that it handles all dependencies automatically, but it's already the case in botcraft during the cmake configuration process. The other advantage is that it's easier to integrate in some projects, but once again, you can add botcraft with only two lines of cmake:
```cmake
add_subdirectory(Botcraft)
target_link_libraries(my_project botcraft)
```
- having multiple versions of a package on vcpkg means having multiple packages. For example, OpenCV has 4 different packages. For botcraft, it means having 26 of them for all versions from 1.12.2 to 1.19.2. And adding between 4 and 10 per years, depending on how many minecraft updates there are. This also means that everytime an update of botcraft is made, one needs to create 26+ PR on vcpkg repo. This looks like a huge time investment and doesn't seem to scale well.
- creating a PR on vcpkg repo requires to sign a [legal document](https://cla.microsoft.com/) with Microsoft and I'm not really confortable doing that as I'm not a lawyer and don't understand all the consequences of it.

For these reasons, I won't consider porting botcraft to vcpkg myself. Obviously, I could be wrong on some points as I don't really use vcpkg, but this is my point of view at the moment.

Of course, if you or anyone else with more knowledge of vcpkg wants to do a clean community port of botcraft to vcpkg that would be nice. But I won't take the time to do (and maintain) it.
