### ISSUE TITLE
Fabric server support

### ISSUE THREAD

**Issue by MKI5000** [adepierre/Botcraft#94]
I used the AFK example and tried to connect to my Minecraft server running with Fabric 1.19 and it couldn't log in.
The server quit the connection with a ```Took too long to log in``` error. Joining vanilla servers worked.

I investigated and used SniffCraft to find out that the server sends a custom query during login wich doesn't get handled / responded to.

SniffCraft logs:
```
[0:0:0:0] [C --> S] Client Intention
[0:0:0:0] [C --> S] Hello
[0:0:0:13] [S --> C] Login Compression
[0:0:0:13] [S --> C] Custom Query
{
    "data": "Vector of 1 unsigned char",
    "identifier": {
        "name": "early_registration",
        "namespace": "fabric-networking-api-v1"
    },
    "transaction_id": 0
}
Session closed
```

The vanilla Minecraft client then responds with a custom query with an empty array and the authentication procedure starts.
```
...
[0:0:0:103] [C --> S] Custom Query
{
    "data": "Vector of 0 unsigned char",
    "transaction_id": 0
}
[0:0:0:109] [S --> C] Game Profile
[0:0:0:145] [S --> C] Login
...
```

I've already tried to quickly add the handling of those custom query packets (just by always responding with an empty array to client bound custom queries) in the NetworkManager and it fully worked afterwards. But I don't know if that causes troubles somewhere else.

To reproduce this issue the Fabric server has to have the FabricAPI mod installed.

**Comment by adepierre** [comment]
Thanks for the detailed report and solution!

I'll try to reproduce it and find a _clean_ solution using what you described. Do you know by any chance if there is a documentation about this custom query of the fabric api mod?

**Comment by MKI5000** [comment]
Thats good :)
But I don't know any documentation about the Fabric API.
My closest guess to where that query comes from would be [this code](https://github.com/FabricMC/fabric/blob/1.19/fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/NetworkingImpl.java).

**Comment by adepierre** [comment]
Ok fixed it locally, will be pushed on master with the next modif. The issue will be closed with the push.

Here is the diff in case you need it:

```diff
diff --git a/botcraft/include/botcraft/Network/NetworkManager.hpp b/botcraft/include/botcraft/Network/NetworkManager.hpp
index 2ee7816..9959095 100644
--- a/botcraft/include/botcraft/Network/NetworkManager.hpp
+++ b/botcraft/include/botcraft/Network/NetworkManager.hpp
@@ -39,6 +39,9 @@ namespace Botcraft
         virtual void Handle(ProtocolCraft::ClientboundGameProfilePacket& msg) override;
         virtual void Handle(ProtocolCraft::ClientboundHelloPacket& msg) override;
         virtual void Handle(ProtocolCraft::ClientboundKeepAlivePacket& msg) override;
+#if PROTOCOL_VERSION > 340
+        virtual void Handle(ProtocolCraft::ClientboundCustomQueryPacket& msg) override;
+#endif
 
     private:
         std::vector<ProtocolCraft::Handler*> subscribed;
diff --git a/botcraft/src/Network/NetworkManager.cpp b/botcraft/src/Network/NetworkManager.cpp
index 3be463f..b56075e 100644
--- a/botcraft/src/Network/NetworkManager.cpp
+++ b/botcraft/src/Network/NetworkManager.cpp
@@ -294,4 +294,23 @@ namespace Botcraft
         keep_alive_msg->SetId_(msg.GetId_());
         Send(keep_alive_msg);
     }
-}
\ No newline at end of file
+
+#if PROTOCOL_VERSION > 340
+    void NetworkManager::Handle(ProtocolCraft::ClientboundCustomQueryPacket& msg)
+    {
+        // Vanilla like response when asked by fabric API
+        // Not implemented in fabric before December 05 2020,
+        // so not necessary before version 1.16.4
+#if PROTOCOL_VERSION > 753
+        if (msg.GetIdentifier().GetFull() == "fabric-networking-api-v1:early_registration")
+        {
+            std::shared_ptr<ProtocolCraft::ServerboundCustomQueryPacket> custom_query_response = std::make_shared<ProtocolCraft::ServerboundCustomQueryPacket>();
+            custom_query_response->SetTransactionId(msg.GetTransactionId());
+            custom_query_response->SetData({});
+            Send(custom_query_response);
+            return;
+        }
+#endif
+    }
+#endif
+}
```

**Comment by MKI5000** [comment]
Okay, nice.
Thank you for the really quick response and fix.
