### ISSUE TITLE
1.8 support?

### ISSUE THREAD

**Issue by rogermiranda1000** [adepierre/Botcraft#95]
Do you plan to add support on Minecraft 1.8?

**Comment by adepierre** [comment]
Hello!

Not really. It's already quite painful to keep 1.12.2 around while it's very different from 1.13+ versions. So I don't really want to add and maintain all other versions down to 1.0.

Out of curiosity, what would be the usecase for bots in such an old version?

**Comment by rogermiranda1000** [comment]
> Out of curiosity, what would be the usecase for bots in such an old version?

I'm trying to build a testing environment for Minecraft plugins as a university project and I want it to be compatible from 1.8 to the latest version.
Your bot caught my attention (for the client side of the project) because it seems well documented, updated and with a lot of functionalities. That's why I was wondering that.

**Comment by adepierre** [comment]
Oh I see. I think you could try mineflayer. They support from 1.8 I think and they have a lot of docs and a bigger community to help too.
