### ISSUE TITLE
question: is this error caused by a special minecraft version?

### ISSUE THREAD

**Issue by folkertvanheusden** [adepierre/Botcraft#98]
[2022-11-02 20:44:00.704] [INFO] [NetworkPacketProcessing(139846432933440)] ConnectionClient.cpp(73): Disconnect during login with reason: {"translate":"disconnect.genericReason","with":["Internal Exception: io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed (20 > 16)"]}

**Comment by adepierre** [comment]
If I had to guess I'd say you're trying to connect with a username with 20 characters, which is longer than the 16 accepted by the server.

**Comment by folkertvanheusden** [comment]
Hmmm, I tried both:

McAutoBot123

***@***.***

Which should be the same user.

**Comment by adepierre** [comment]
McAutoBot123 should work for servers in offline mode. If you want to connect to a server in online mode, you should either use an empty login (you will be prompted with instructions to enter your credentials at runtime), or set ``force_microsoft_account`` to true when calling connect. See this [wiki page](https://github.com/adepierre/Botcraft/wiki/Connection) for details.

**Comment by folkertvanheusden** [comment]
And now it works perfectly!
I'll write it down, I have a deja-vu feeling with this.
Thank you very much.
